### ISSUE TITLE
Windows support in 2.0.x

### ISSUE THREAD

**Issue by ow--** [dman777/gulp-newy#5]
Hello again!

Version 2.0.x is breaking on Windows so far, I'm afraid, since paths aren't rooted in `/`. I've no idea if there are any de facto solutions for this for Node modules or gulp plugins, but something akin to the following snippet seems like it would work on this occasion:

```js
var parsed = path.parse(destinationFile);
var directories = parsed.dir.substr(parsed.root.length).split(path.sep);
var pathBuild = parsed.root;
var directoryMissing = directories.some(...);
```

**Comment by dman777** [comment]
Hi! Thanks for the heads up! I'm sorry, I never use Windows :( I'm a Linux guy myself :) I'll probably just leave it for Unix like OSs only.
